
const num = 100,demo = 'a';

try{
    console.log(num/demo);
    consple.log(a);
}

catch(error) {
  console.log('en error caught');
  console.log("Error message" + error);
}

finally{
    console,log("finally will ececute every time");
}